SELECT address.id,
address.addresstype as addresstype,
address.firstname,
address.lastname,
address.address,
address.city,
address.state,
address.zip,
address.country,
address.institution_string,
address.email,
address.fax,
address.phone,
CAST(address.purchase_id as Integer) as purchase_id,
-- address.username,
-- address.authority,
-- address.hidden,
-- address.created,
-- address.modified,
address.address2
FROM address
